### ISSUE TITLE
Command structure

### ISSUE THREAD

**Issue by uainformatsia** [simonhuwiler/uawardata#1]
Thanks for your great work, I hope my remarks here are in the right place.
A few comments on command structure:
* You list the 200th MRB as 6th CAA. Isn't that brigade usually part of the 14th Army Corps?
* You list the 126th SGCDB as 49th CAA instead of 22nd Army Corps
* You list the 34th SMRB and the 205th SMRB as 22nd Army Corps instead of 49th CAA
* the 20th GMRD should be 8th CAA, as far as I know.
I am sure you had specific reasons for your decisions, maybe you can explain them.
* Furthermore, your full list does not include the 70th MRR (42nd GMRD). That regiment reportedly suffered a heavy defeat, maybe you can add it?

**Comment by uainformatsia** [comment]
The 752nd GMRR is listed as subordinate to 3rd MRR, should be 3rd MRD

A few more units that were mentioned in battle reports but do not show up in your full list of units (probably for a reason):
13th GTR (4th GTD)
30th MRB (2nd CAA)
136th GMRB (58th CAA)
239th GTR (90th GTD)
291st GMRR (42nd GMRD)
429rd MRR (19th MRD)
488th MRR (144th MRD)
12th Guards Engineering Brigade (Central Military District)
45th Guards Engineering Brigade (Western Military District)
40th Naval Infantry Brigade (Pacific Fleet) [probably not yet deployed, but was mentioned on March 19th as repleneshing losses of other units]
61st Naval Infantry Brigade (Northern Fleet)
336th Guards Naval Infantry Brigade (Baltic Fleet)
177th Naval Infantry Regiment (Caspian Flotilla)

**Comment by hschlottman** [comment]
> Thanks for your great work, I hope my remarks here are in the right place. A few comments on command structure:
> 
> * You list the 200th MRB as 6th CAA. Isn't that brigade usually part of the 14th Army Corps?
> * You list the 126th SGCDB as 49th CAA instead of 22nd Army Corps
> * You list the 34th SMRB and the 205th SMRB as 22nd Army Corps instead of 49th CAA
> * the 20th GMRD should be 8th CAA, as far as I know.
>   I am sure you had specific reasons for your decisions, maybe you can explain them.
> * Furthermore, your full list does not include the 70th MRR (42nd GMRD). That regiment reportedly suffered a heavy defeat, maybe you can add it?

Yes, for the units you listed, it is my assessment they are operationally controlled by who I've put them as "subordinate to", normally, yes they belong to someone else. This assessment is based off a set of captured Russian plans. 

I wasn't tracking 70th, do you know where this defeat happened? I'll look into.

For the fastest response time, try sending me a message on twitter.

**Comment by hschlottman** [comment]
> The 752nd GMRR is listed as subordinate to 3rd MRR, should be 3rd MRD
> 
> A few more units that were mentioned in battle reports but do not show up in your full list of units (probably for a reason): 13th GTR (4th GTD) 30th MRB (2nd CAA) 136th GMRB (58th CAA) 239th GTR (90th GTD) 291st GMRR (42nd GMRD) 429rd MRR (19th MRD) 488th MRR (144th MRD) 12th Guards Engineering Brigade (Central Military District) 45th Guards Engineering Brigade (Western Military District) 40th Naval Infantry Brigade (Pacific Fleet) [probably not yet deployed, but was mentioned on March 19th as repleneshing losses of other units] 61st Naval Infantry Brigade (Northern Fleet) 336th Guards Naval Infantry Brigade (Baltic Fleet) 177th Naval Infantry Regiment (Caspian Flotilla)

Largely because I don't know where those units are located at the present time, if you've seen something, feel free to send me a message on Twitter.
