### ISSUE TITLE
uawardata.com is exposing Ukraine locations

### ISSUE THREAD

**Issue by jjarokergc** [simonhuwiler/uawardata#5]
Would you please explain if the uawardata.com website is intentionally exposing positions of Ukraine military equipment?  As of the data of April 27 (approximately), I notice that the website shows both Russian and Ukrainian positions. Prior to April 27, only RU data was shown.

Is this intentional, or am I misunderstanding the data.
![image](https://user-images.githubusercontent.com/1794056/167271726-faf19805-2f19-4fab-b51c-32b55cca0a7e.png)

**Comment by simonhuwiler** [comment]
Hi Jon
You do not misunderstanding the data, we show ukraine positions. But there is a difference, what we show. As mentioned in the readme:
* Only data from official government sources
* We do no other OSINT analysis (equipment, .etc.)
* Coordinates will be only 3 significant figures
*
So we only show generally known information.
