### ISSUE TITLE
Feedback: Incredible work - thank you!

### ISSUE THREAD

**Issue by sgofferj** [simonhuwiler/uawardata#6]
Hi,

I don't have any other way to contact you as I'm not on Twitter, so I use this ticket to thank you (both) for the incredible work you're doing here! I can only imagine the effort it takes to follow this mess and keep the data uptodate.
I mainly use the GeoJSON data for my own situational awareness display.

-Stefan

**Comment by simonhuwiler** [comment]
Hi Stefan

Thank you for your kind message!

Best regards,
Simon

**Comment by rubennaatje** [comment]
@simonhuwiler While I don't know if it's due to your technology partner but this is the fastest and smoothest online map i've ever seen. Really impressed. 

Thanks for your work and esp. for making it open source!

**Comment by simonhuwiler** [comment]
@rubennaatje Thank you for your kind message! Appreciate it a lot!
