### ISSUE TITLE
Long term maintenance? 

### ISSUE THREAD

**Issue by phornstein** [simonhuwiler/uawardata#7]
Is there a plan to continue to update this repo? This is fantastic information, but before integrating it into an OSINT project I am working on I want to ensure that it's maintained.

**Comment by simonhuwiler** [comment]
Hi Parker
This project is a bit dormant at the moment. At the moment, however, we are thinking about expanding the map with analyses of the manpower of the units. But this will take a few more weeks.
I wonder: What are you working on? I am always interested in new projects.

**Comment by phornstein** [comment]
Simon,
thanks for the response. I work for Esri (I noticed you have some ArcGIS focused features in here which we love). We've been looking at potentially building some automated proofs of concept using this OSINT dataset: https://github.com/zhukovyuri/VIINA/ to identify artillery locations by doing some backwards range rings from points of impact and looking at intersects. We need a good dataset we could use to help potentially narrow down probable firing locations. I just stumbled on your repo a couple days ago and we thought it would a great dataset to help out with context and enrichment.... also I have some other guys who would be very interested in loading this into a Knowledge Graph to try and connect with other reporting/events.

**Comment by simonhuwiler** [comment]
Hi Parker

Yes, we have ArcGIS features built in - even though we use QGIS (sorry for that...).

Your project sounds exciting! Can you keep me up to date? Maybe we can use it for our reporting...

I didn't know about the VIINA dataset. Looks promising, thank you! The following datasets might also be helpful:

* liveuamap.com records many attacks. They have built a system that automatically monitors social media activity. However, the coordinates are not super accurate. Access to the data costs something.
* geoconfirmed.org has the most accurate data. However, the data is not categorised and a few days behind.
* Acled (https://acleddata.com/ukraine-conflict-monitor/) publishes similar data as VIINA. But I think you have to ask them for it. Not sure.

**Comment by kerryrobinson** [comment]
Just to chime in regarding ArcGIS... in the latest version of ArcGIS (Q1 2023) we now support SIDC characters less than 15 characters. :)  But thanks for adding the extra field, @simonhuwiler!

**Comment by simonhuwiler** [comment]
Very nice!

**Comment by phornstein** [comment]
Simon, 

forget to hit submit! The geoconfirmed site is new to me and has been incredibly useful. Thank you! Feel free to reach out if you ever want to chat about Esri can help with some of your projects!

**Comment by kerickso85** [comment]
Just chiming in from the peanut gallery, but I'm quite happy I am sub'd and receive the discourse. @simonhuwiler please do continue to support the effort. I'm happy to see you're cross platform too!
